# Generated by Django 5.1.3 on 2024-11-21 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Router",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "ipv6_address",
                    models.GenericIPAddressField(protocol="IPv6", unique=True),
                ),
                (
                    "connected_routers",
                    models.ManyToManyField(blank=True, to="simulation.router"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "ipv6_address",
                    models.GenericIPAddressField(protocol="IPv6", unique=True),
                ),
                (
                    "connected_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="devices",
                        to="simulation.router",
                    ),
                ),
            ],
        ),
    ]
